kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-local-1
networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    extraPortMappings:
    - containerPort: 6443
      hostPort: 10443
      listenAddress: "127.0.0.1"
      protocol: TCP
    - containerPort: 30090
      hostPort: 9090
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30950
      hostPort: 8089
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30951
      hostPort: 8081
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30952
      hostPort: 8080
      listenAddress: "0.0.0.0"
      protocol: TCP
    - containerPort: 30953
      hostPort: 8443
      listenAddress: "0.0.0.0"
      protocol: TCP
